//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cantina
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public int Id { get; set; }
        public string cliente { get; set; }
        public int quentinhasp { get; set; }
        public int quentinhasm { get; set; }
        public int quentinhasg { get; set; }
        public decimal entrega { get; set; }
        public decimal total { get; set; }
    }
}
